spring.application.name=VibeWall


# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN
logging.level.org.mongodb.driver=INFO

server.servlet.context-path=/api/v3

# AI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=${OPENAI_CHAT_MODEL:gpt-4.1-mini}

server.port=${SERVER_PORT:8080}

# SSL
server.ssl.enabled=false

# Redis
spring.cache.type=redis
spring.data.redis.url=${SPRING_DATA_REDIS_URL}

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# Gemini
gemini.api.key=${GEMINI_API_KEY}

# Security
jwt.secret=${JWT_SECRET}
encryption.key=${ENCRYPTION_KEY}

# CORS
allowed.origins=${ALLOWED_ORIGINS:http://localhost:5173}

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
