spring.application.name=VibeWall
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=vibewall

# Enable MongoDB query logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO

server.servlet.context-path=/api/v2

